lib/elixir_anki_web/router.ex
defmodule ElixirAnkiWeb.Router do
  use ElixirAnkiWeb, :router
  use ExAdmin.Router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  scope "/admin", ExAdmin do
    pipe_through(:browser)
    admin_routes()
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", ElixirAnkiWeb do
    # Use the default browser stack
    pipe_through(:browser)

    resources("/users", UserController)

    get("/", PageController, :index)
  end

  # Other scopes may use custom stacks.
  # scope "/api", ElixirAnkiWeb do
  #   pipe_through :api
  # end
end

lib/elixir_anki/user.ex
defmodule ElixirAnki.User do
  use Ecto.Schema
  import Ecto.Changeset

  @mail_regex ~r/^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$/

  schema "users" do
    field(:email, :string)
    field(:password_hash, :string)
    field(:username, :string)

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:username, :email, :password_hash])
    |> validate_required([:username, :email, :password_hash])
    |> validate_format(:email, @mail_regex)
    |> unique_constraint(:email)
  end
end

lib/elixir_anki_web/views/user_view.ex
defmodule ElixirAnkiWeb.UserView do
  use ElixirAnkiWeb, :view
end

lib/elixir_anki_web/templates/user/edit.html.eex
<h2>Edit User</h2>

<%= render "form.html", Map.put(assigns, :action, user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: user_path(@conn, :index) %></span>

lib/elixir_anki_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :username, class: "control-label" %>
    <%= text_input f, :username, class: "form-control" %>
    <%= error_tag f, :username %>
  </div>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= label f, :password_hash, class: "control-label" %>
    <%= text_input f, :password_hash, class: "form-control" %>
    <%= error_tag f, :password_hash %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/elixir_anki_web/templates/user/index.html.eex
<h2>Listing Users</h2>

<table class="table">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Password hash</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td><%= user.password_hash %></td>

      <td class="text-right">
        <span><%= link "Show", to: user_path(@conn, :show, user), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: user_path(@conn, :edit, user), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New User", to: user_path(@conn, :new) %></span>

lib/elixir_anki_web/templates/user/new.html.eex
<h2>New User</h2>

<%= render "form.html", Map.put(assigns, :action, user_path(@conn, :create)) %>

<span><%= link "Back", to: user_path(@conn, :index) %></span>

lib/elixir_anki_web/templates/user/show.html.eex
<h2>Show User</h2>

<ul>

  <li>
    <strong>Username:</strong>
    <%= @user.username %>
  </li>

  <li>
    <strong>Email:</strong>
    <%= @user.email %>
  </li>

  <li>
    <strong>Password hash:</strong>
    <%= @user.password_hash %>
  </li>

</ul>

<span><%= link "Edit", to: user_path(@conn, :edit, @user) %></span>
<span><%= link "Back", to: user_path(@conn, :index) %></span>